language: java

env:
- TERM=dumb

before_install:

# use Gradle 1.7 
- wget http://services.gradle.org/distributions/gradle-1.7-bin.zip
- unzip gradle-1.7-bin.zip
- export GRADLE_HOME=$PWD/gradle-1.7
- export PATH=$GRADLE_HOME/bin:$PATH
- wget https://contexttoolkit.googlecode.com/files/contexttoolkit-2.0.jar
- mvn install:install-file -Dfile=$PWD/contexttoolkit-2.0.jar -DgroupId=context.tool.kit -DartifactId=contexttoolkit -Dversion=1 -Dpackaging=jar

after_success:
- mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura
