/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.GUI;

import br.ufrn.services.AtualizaMonitor;

/**
 *
 * @author Zeff
 */
public class MonitorCidade extends javax.swing.JFrame implements AtualizaMonitor{

    /**
     * Creates new form MonitorCidade
     */
    
    private static final MonitorCidade MONITOR_CIDADE = new MonitorCidade();
    
    public static MonitorCidade getInstance(){
        MONITOR_CIDADE.setVisible(true);
        return MONITOR_CIDADE;
    }
    
    private MonitorCidade() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        LabeAciA1 = new javax.swing.JLabel();
        LabeAgeA1 = new javax.swing.JLabel();
        LabeSomA1 = new javax.swing.JLabel();
        LabeFogoA1 = new javax.swing.JLabel();
        LabelLixoA1 = new javax.swing.JLabel();
        LabeChuvaA1 = new javax.swing.JLabel();
        LabeTempA1 = new javax.swing.JLabel();
        LabePolA1 = new javax.swing.JLabel();
        LabelCarroA1 = new javax.swing.JLabel();
        LabelSecQueA1 = new javax.swing.JLabel();
        LabelUmiA1 = new javax.swing.JLabel();
        Balao1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        LabelLixoA2 = new javax.swing.JLabel();
        LabeChuvaA2 = new javax.swing.JLabel();
        LabeSomA2 = new javax.swing.JLabel();
        LabeFogoA2 = new javax.swing.JLabel();
        LabeAciA2 = new javax.swing.JLabel();
        LabePolA2 = new javax.swing.JLabel();
        LabeTempA2 = new javax.swing.JLabel();
        LabeAgeA2 = new javax.swing.JLabel();
        LabelCarroA2 = new javax.swing.JLabel();
        LabelSecQueA2 = new javax.swing.JLabel();
        LabelUmiA2 = new javax.swing.JLabel();
        Balao2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        LabelLixoA3 = new javax.swing.JLabel();
        LabeChuvaA3 = new javax.swing.JLabel();
        LabeSomA3 = new javax.swing.JLabel();
        LabeFogoA3 = new javax.swing.JLabel();
        LabeAciA3 = new javax.swing.JLabel();
        LabePolA3 = new javax.swing.JLabel();
        LabeTempA3 = new javax.swing.JLabel();
        LabeAgeA3 = new javax.swing.JLabel();
        LabelCarroA3 = new javax.swing.JLabel();
        LabelSecQueA3 = new javax.swing.JLabel();
        LabelUmiA3 = new javax.swing.JLabel();
        Balao3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        LabeAgeA4 = new javax.swing.JLabel();
        LabeTempA4 = new javax.swing.JLabel();
        LabelLixoA4 = new javax.swing.JLabel();
        LabeChuvaA4 = new javax.swing.JLabel();
        LabeSomA4 = new javax.swing.JLabel();
        LabeFogoA4 = new javax.swing.JLabel();
        LabeAciA4 = new javax.swing.JLabel();
        LabePolA4 = new javax.swing.JLabel();
        LabelCarroA4 = new javax.swing.JLabel();
        LabelSecQueA4 = new javax.swing.JLabel();
        LabelUmiA4 = new javax.swing.JLabel();
        Balao4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        LabelCarroA5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelUmiA5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setOpaque(false);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        LabeAciA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemAcida.png"))); // NOI18N
        jPanel5.add(LabeAciA1);
        LabeAciA1.setBounds(180, 10, 32, 35);

        LabeAgeA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/CaminhaoDesativado.png"))); // NOI18N
        jPanel5.add(LabeAgeA1);
        LabeAgeA1.setBounds(60, 50, 32, 32);

        LabeSomA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemBuzina.png"))); // NOI18N
        jPanel5.add(LabeSomA1);
        LabeSomA1.setBounds(100, 10, 32, 35);

        LabeFogoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemFogo.png"))); // NOI18N
        jPanel5.add(LabeFogoA1);
        LabeFogoA1.setBounds(140, 10, 32, 35);

        LabelLixoA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoVazia.png"))); // NOI18N
        jPanel5.add(LabelLixoA1);
        LabelLixoA1.setBounds(20, 10, 32, 35);

        LabeChuvaA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemChuva.png"))); // NOI18N
        jPanel5.add(LabeChuvaA1);
        LabeChuvaA1.setBounds(60, 10, 32, 35);

        LabeTempA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp3.png"))); // NOI18N
        jPanel5.add(LabeTempA1);
        LabeTempA1.setBounds(20, 50, 32, 32);

        LabePolA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado1.png"))); // NOI18N
        jPanel5.add(LabePolA1);
        LabePolA1.setBounds(220, 10, 32, 35);

        LabelCarroA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carroSem.png"))); // NOI18N
        jPanel5.add(LabelCarroA1);
        LabelCarroA1.setBounds(100, 50, 30, 30);

        LabelSecQueA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon-sem.png"))); // NOI18N
        jPanel5.add(LabelSecQueA1);
        LabelSecQueA1.setBounds(140, 50, 30, 30);

        LabelUmiA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/drop.png"))); // NOI18N
        jPanel5.add(LabelUmiA1);
        LabelUmiA1.setBounds(180, 40, 32, 40);

        Balao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/balao 1.png"))); // NOI18N
        Balao1.setText("jLabel2");
        jPanel5.add(Balao1);
        Balao1.setBounds(0, 0, 313, 158);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 30, 340, 180);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(null);

        LabelLixoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoVazia.png"))); // NOI18N
        jPanel8.add(LabelLixoA2);
        LabelLixoA2.setBounds(50, 20, 32, 32);

        LabeChuvaA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemChuva.png"))); // NOI18N
        jPanel8.add(LabeChuvaA2);
        LabeChuvaA2.setBounds(90, 20, 32, 32);

        LabeSomA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemBuzina.png"))); // NOI18N
        jPanel8.add(LabeSomA2);
        LabeSomA2.setBounds(130, 20, 32, 32);

        LabeFogoA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemFogo.png"))); // NOI18N
        jPanel8.add(LabeFogoA2);
        LabeFogoA2.setBounds(170, 20, 32, 32);

        LabeAciA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemAcida.png"))); // NOI18N
        jPanel8.add(LabeAciA2);
        LabeAciA2.setBounds(210, 20, 32, 32);

        LabePolA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado1.png"))); // NOI18N
        jPanel8.add(LabePolA2);
        LabePolA2.setBounds(250, 20, 32, 32);

        LabeTempA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp3.png"))); // NOI18N
        jPanel8.add(LabeTempA2);
        LabeTempA2.setBounds(50, 60, 32, 32);

        LabeAgeA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/CaminhaoDesativado.png"))); // NOI18N
        jPanel8.add(LabeAgeA2);
        LabeAgeA2.setBounds(90, 60, 32, 32);

        LabelCarroA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carroSem.png"))); // NOI18N
        jPanel8.add(LabelCarroA2);
        LabelCarroA2.setBounds(130, 60, 30, 30);

        LabelSecQueA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon-sem.png"))); // NOI18N
        jPanel8.add(LabelSecQueA2);
        LabelSecQueA2.setBounds(170, 60, 30, 30);

        LabelUmiA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/drop.png"))); // NOI18N
        jPanel8.add(LabelUmiA2);
        LabelUmiA2.setBounds(210, 50, 32, 40);

        Balao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/balao 2.png"))); // NOI18N
        jPanel8.add(Balao2);
        Balao2.setBounds(0, 0, 320, 169);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(22, 12, 320, 180);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(440, 10, 340, 180);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(null);

        LabelLixoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoVazia.png"))); // NOI18N
        jPanel9.add(LabelLixoA3);
        LabelLixoA3.setBounds(60, 20, 32, 32);

        LabeChuvaA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemChuva.png"))); // NOI18N
        jPanel9.add(LabeChuvaA3);
        LabeChuvaA3.setBounds(100, 20, 32, 32);

        LabeSomA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemBuzina.png"))); // NOI18N
        jPanel9.add(LabeSomA3);
        LabeSomA3.setBounds(140, 20, 32, 32);

        LabeFogoA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemFogo.png"))); // NOI18N
        jPanel9.add(LabeFogoA3);
        LabeFogoA3.setBounds(180, 20, 32, 32);

        LabeAciA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemAcida.png"))); // NOI18N
        jPanel9.add(LabeAciA3);
        LabeAciA3.setBounds(220, 20, 32, 32);

        LabePolA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado1.png"))); // NOI18N
        jPanel9.add(LabePolA3);
        LabePolA3.setBounds(260, 20, 32, 32);

        LabeTempA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp3.png"))); // NOI18N
        jPanel9.add(LabeTempA3);
        LabeTempA3.setBounds(60, 60, 32, 32);

        LabeAgeA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/CaminhaoDesativado.png"))); // NOI18N
        jPanel9.add(LabeAgeA3);
        LabeAgeA3.setBounds(100, 60, 32, 32);

        LabelCarroA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carroSem.png"))); // NOI18N
        jPanel9.add(LabelCarroA3);
        LabelCarroA3.setBounds(140, 60, 30, 30);

        LabelSecQueA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon-sem.png"))); // NOI18N
        jPanel9.add(LabelSecQueA3);
        LabelSecQueA3.setBounds(180, 60, 30, 30);

        LabelUmiA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/drop.png"))); // NOI18N
        jPanel9.add(LabelUmiA3);
        LabelUmiA3.setBounds(220, 50, 32, 40);

        Balao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/balao 3.png"))); // NOI18N
        jPanel9.add(Balao3);
        Balao3.setBounds(10, 8, 320, 160);

        jPanel4.add(jPanel9);
        jPanel9.setBounds(10, 10, 340, 170);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(440, 200, 330, 180);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(null);

        LabeAgeA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/CaminhaoDesativado.png"))); // NOI18N
        jPanel10.add(LabeAgeA4);
        LabeAgeA4.setBounds(70, 60, 32, 32);

        LabeTempA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp3.png"))); // NOI18N
        jPanel10.add(LabeTempA4);
        LabeTempA4.setBounds(30, 60, 32, 32);

        LabelLixoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoVazia.png"))); // NOI18N
        jPanel10.add(LabelLixoA4);
        LabelLixoA4.setBounds(30, 20, 32, 32);

        LabeChuvaA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemChuva.png"))); // NOI18N
        jPanel10.add(LabeChuvaA4);
        LabeChuvaA4.setBounds(70, 20, 32, 32);

        LabeSomA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemBuzina.png"))); // NOI18N
        jPanel10.add(LabeSomA4);
        LabeSomA4.setBounds(110, 20, 32, 32);

        LabeFogoA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/SemFogo.png"))); // NOI18N
        jPanel10.add(LabeFogoA4);
        LabeFogoA4.setBounds(150, 20, 32, 32);

        LabeAciA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemSemAcida.png"))); // NOI18N
        jPanel10.add(LabeAciA4);
        LabeAciA4.setBounds(190, 20, 32, 32);

        LabePolA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado1.png"))); // NOI18N
        jPanel10.add(LabePolA4);
        LabePolA4.setBounds(230, 20, 32, 32);

        LabelCarroA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carroSem.png"))); // NOI18N
        jPanel10.add(LabelCarroA4);
        LabelCarroA4.setBounds(110, 60, 30, 30);

        LabelSecQueA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon-sem.png"))); // NOI18N
        jPanel10.add(LabelSecQueA4);
        LabelSecQueA4.setBounds(150, 60, 30, 30);

        LabelUmiA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/drop.png"))); // NOI18N
        jPanel10.add(LabelUmiA4);
        LabelUmiA4.setBounds(190, 50, 32, 40);

        Balao4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/balao 4.png"))); // NOI18N
        jPanel10.add(Balao4);
        Balao4.setBounds(10, 11, 311, 158);

        jPanel6.add(jPanel10);
        jPanel10.setBounds(11, 12, 320, 170);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(22, 261, 340, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/rio-grande-norte definitivo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, -10, 800, 600);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Legenda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DECODE", 0, 36))); // NOI18N

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Caminhao.png"))); // NOI18N
        jLabel47.setText("Coleta de Lixo");

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/temp5.png"))); // NOI18N
        jLabel48.setText("Temperatura");

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/LixoEnchendo.png"))); // NOI18N
        jLabel49.setText("Lixeira");

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemChuva.png"))); // NOI18N
        jLabel50.setText("Chuva");

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Buzina.png"))); // NOI18N
        jLabel51.setText("Poluição Sonora");

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/Fogo.png"))); // NOI18N
        jLabel52.setText("Fogo");

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemAcida.png"))); // NOI18N
        jLabel53.setText("Chuva Ácida");

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/NuvemVerdeEstado6.png"))); // NOI18N
        jLabel54.setText("Poluição do Ar");

        LabelCarroA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/carro.png"))); // NOI18N
        LabelCarroA5.setText("Carros");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/eyes-on-fire-icon.png"))); // NOI18N
        jLabel6.setText("Quente e Seco");

        LabelUmiA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufrn/Imagens/drop.png"))); // NOI18N
        LabelUmiA5.setText("Umidade");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel49)
                        .addComponent(jLabel48)
                        .addComponent(jLabel53)
                        .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel52)
                        .addComponent(jLabel50)
                        .addComponent(jLabel47)
                        .addComponent(jLabel54)
                        .addComponent(LabelCarroA5)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(LabelUmiA5))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addGap(4, 4, 4)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCarroA5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUmiA5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(800, 40, 144, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitorCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitorCidade().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balao1;
    private javax.swing.JLabel Balao2;
    private javax.swing.JLabel Balao3;
    private javax.swing.JLabel Balao4;
    private javax.swing.JLabel LabeAciA1;
    private javax.swing.JLabel LabeAciA2;
    private javax.swing.JLabel LabeAciA3;
    private javax.swing.JLabel LabeAciA4;
    private javax.swing.JLabel LabeAgeA1;
    private javax.swing.JLabel LabeAgeA2;
    private javax.swing.JLabel LabeAgeA3;
    private javax.swing.JLabel LabeAgeA4;
    private javax.swing.JLabel LabeChuvaA1;
    private javax.swing.JLabel LabeChuvaA2;
    private javax.swing.JLabel LabeChuvaA3;
    private javax.swing.JLabel LabeChuvaA4;
    private javax.swing.JLabel LabeFogoA1;
    private javax.swing.JLabel LabeFogoA2;
    private javax.swing.JLabel LabeFogoA3;
    private javax.swing.JLabel LabeFogoA4;
    private javax.swing.JLabel LabePolA1;
    private javax.swing.JLabel LabePolA2;
    private javax.swing.JLabel LabePolA3;
    private javax.swing.JLabel LabePolA4;
    private javax.swing.JLabel LabeSomA1;
    private javax.swing.JLabel LabeSomA2;
    private javax.swing.JLabel LabeSomA3;
    private javax.swing.JLabel LabeSomA4;
    private javax.swing.JLabel LabeTempA1;
    private javax.swing.JLabel LabeTempA2;
    private javax.swing.JLabel LabeTempA3;
    private javax.swing.JLabel LabeTempA4;
    private javax.swing.JLabel LabelCarroA1;
    private javax.swing.JLabel LabelCarroA2;
    private javax.swing.JLabel LabelCarroA3;
    private javax.swing.JLabel LabelCarroA4;
    private javax.swing.JLabel LabelCarroA5;
    private javax.swing.JLabel LabelLixoA1;
    private javax.swing.JLabel LabelLixoA2;
    private javax.swing.JLabel LabelLixoA3;
    private javax.swing.JLabel LabelLixoA4;
    private javax.swing.JLabel LabelSecQueA1;
    private javax.swing.JLabel LabelSecQueA2;
    private javax.swing.JLabel LabelSecQueA3;
    private javax.swing.JLabel LabelSecQueA4;
    private javax.swing.JLabel LabelUmiA1;
    private javax.swing.JLabel LabelUmiA2;
    private javax.swing.JLabel LabelUmiA3;
    private javax.swing.JLabel LabelUmiA4;
    private javax.swing.JLabel LabelUmiA5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void atualizaNivelPoluicao(Integer area, String levelPollution) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaFluxoVeiculos(Integer area) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaProbabilidaDeChuva(Integer area) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaChuvaAcida(Integer area, String localAcidRain) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaQuantidadeRuido(Integer area, Integer noise) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaTemperatura(Integer area, float temperature) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaClimaBom(Integer area, boolean clima) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaIncidenciaDeIncendio(Integer area, boolean isFire) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaClimaQuenteESeco(Integer area, boolean hotDry) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaQuantidadeLixo(Integer area, String trash) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void atualizaAgenteProximo(Integer area, String aegntNearName) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    

}
